#! /usr/bin/env ruby
# frozen_string_literal: true

# ######################################################################## #
# File:     exe/usb-cracker
#
# Purpose:  Entry point for the usb-cracker CLI
#
# Created:  9th September 2026
# Updated:  15th September 2026
#
# ######################################################################## #


# ##########################################################
# requires

$:.unshift File.join(File.dirname(__FILE__), '..', 'lib')

require 'usb_cracker/cli'
require 'usb_cracker/prefix'


# ##########################################################
# command-line handling

trap 'INT' do

  $stderr.puts ''

  UsbCracker::Cli.abort 'processing cancelled ...', exit: 130
end

options = UsbCracker::Cli.parse ARGV

UsbCracker::Prefix.read! do |_prefix|

  # Step 5 will search with +options+ here (Unlock.attempt per candidate);
  # PREFIX is wiped in ensure even on abort.
  UsbCracker::Cli.abort 'suffix search is not implemented in this scaffold release'
end


# ############################## end of file ############################# #
