#! /usr/bin/env ruby
# frozen_string_literal: true

# ######################################################################## #
# File:     exe/usb-cracker
#
# Purpose:  Entry point for the usb-cracker CLI
#
# Created:  9th September 2026
# Updated:  15th September 2026
#
# ######################################################################## #


# ##########################################################
# requires

$:.unshift File.join(File.dirname(__FILE__), '..', 'lib')

require 'usb_cracker/cli'


# ##########################################################
# command-line handling

trap 'INT' do

  $stderr.puts ''

  UsbCracker::Cli.abort 'processing cancelled ...', exit: 130
end

UsbCracker::Cli.parse ARGV


# ##########################################################
# main()

UsbCracker::Cli.abort 'search and unlock are not implemented in this scaffold release'


# ############################## end of file ############################# #
